import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useContext, useEffect, useState } from 'react';
import Header from '../../components/Header';
import teste from '../../styles/teste.json';
import { CgArrowLongLeft } from 'react-icons/cg';
import Link from 'next/link';
import styles from '../../styles/Home.module.css';
import { colocarVirgula } from '../../utils/stringFunctions';
import CartContext from '../../context';

export default function Details() {
  const router = useRouter();
  const { productid } = router.query;

  const [product, setProduct] = useState({});
  const [cartProducts, setCartProducts] = useContext(CartContext);
  const [selected, setSelected] = useState();

  useEffect(() => {
    const product = teste.products.filter((product) => product.id == productid);
    setProduct(product[0]);
  }, [productid]);

  return (
    <div>
      <Head>
        <title>details</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Header />
        <section style={{ padding: '1rem 4rem' }}>
          <Link href='/about'>
            <a style={{ display: 'flex', alignItems: 'center' }}>
              <CgArrowLongLeft size={30} />
              <span style={{ marginLeft: '1.5rem' }}>Voltar</span>
            </a>
          </Link>
          <div className={styles.productInfo}>
            <img
              src={product.image}
              alt='product image'
              style={{
                width: '27rem',
                height: 'auto',
                borderRadius: '1rem',
                justifySelf: 'flex-end',
              }}
            />
            <div
              style={{
                width: '27rem',
                display: 'flex',
                flexDirection: 'column',
              }}
            >
              <h2>{product.name}</h2>
              <span style={{color: 'gray'}}>{product.description}</span>
              <span
                style={{
                  marginTop: '1rem',
                  fontWeight: 'bold',
                  fontSize: '1.5rem',
                }}
              >
                R$ {product.price && colocarVirgula(product.price)}
              </span>
              <div
                style={{
                  display: 'flex',
                  justifyContent: 'space-between',
                  width: '80%',
                  alignSelf: 'center',
                  margin: '2rem 0',
                }}
              >
                <button
                  className={`${styles.sizeButton} ${
                    selected === 'XS' && styles.sizeSelected
                  }`}
                  onClick={() => setSelected('XS')}
                >
                  XS
                </button>
                <button
                  className={`${styles.sizeButton} ${
                    selected === 'S' && styles.sizeSelected
                  }`}
                  onClick={() => setSelected('S')}
                >
                  S
                </button>
                <button
                  className={`${styles.sizeButton} ${
                    selected === 'M' && styles.sizeSelected
                  }`}
                  onClick={() => setSelected('M')}
                >
                  M
                </button>
                <button
                  className={`${styles.sizeButton} ${
                    selected === 'L' && styles.sizeSelected
                  }`}
                  onClick={() => setSelected('L')}
                >
                  L
                </button>
                <button
                  className={`${styles.sizeButton} ${
                    selected === 'XL' && styles.sizeSelected
                  }`}
                  onClick={() => setSelected('XL')}
                >
                  XL
                </button>
              </div>
              <button
                className={styles.addToCartButton}
                onClick={() => setCartProducts([...cartProducts, product])}
              >
                Adicionar ao carrinho
              </button>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
