import Head from 'next/head'
import Header from '../Header'
import styles from './Layout.module.css'

export default function Layout({children, pageTitle}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <section className={styles.mainContent}>
            {children}
        </section>
      </main>
    </div>
  )
}
