import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useContext, useEffect, useState } from 'react';
import Header from '../components/Header';
import teste from '../styles/teste.json';
import { CgArrowLongLeft } from 'react-icons/cg';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import CartContext from '../context';

export default function Cart() {
  const [product, setProduct] = useState({});
  const [cartProducts, setCartProducts] = useContext(CartContext);
  const [selected, setSelected] = useState();

  return (
    <div>
      <Head>
        <title>cart</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Header />
        <section style={{ padding: '1rem 4rem' }}>
          <Link href='/about'>
            <a style={{ display: 'flex', alignItems: 'center' }}>
              <CgArrowLongLeft size={30} />
              <span style={{ marginLeft: '1.5rem' }}>Voltar</span>
            </a>
          </Link>
        </section>
      </main>
    </div>
  );
}
